### ISSUE TITLE
About norm_factor in clean3

### ISSUE THREAD

**Issue by Cuixiaojian21** [skelviper/CHARMtools#3]
Zhiyuan，hello！
When I was executing clean3, python reported "ValueError: could not convert string to float: 'chrXb 171031299'". Did something go wrong earlier? I tweaked the details in "CHARMio.py" to make it work. backbone_unit accepts 171031299 of chrXb as its value. Is that okay? And I would also like to know what is your reason for saying "## assume last comment is backbone_unit" and what is your reason for taking only the length of the last chromosome.
Thanks

**Comment by skelviper** [comment]
Hi Xiaojian!
Sorry about the confusion here. Normally, the last line of the header is not the length of the chromosome but the "backbone unit". I guess this problem may be caused by the version of hickit. Please check the output of “hickit -V”. I am using the r291 version. By the way, if you just want to re-analyze HiRES data, you can directly download the 3dg file we calculated on GEO, which can save a lot of time. Hope this answers your question, feel free to re-open the issue if you have other questions.
